services:
  # Define el servicio web para Curiosity
  - type: web
    name: curiosity-chat
    env: python
    plan: free
    
    # Configuración del build
    buildCommand: pip install -r requirements.txt
    
    # Comando para iniciar el servicio
    startCommand: gunicorn app:app
    
    # Variables de entorno
    envVars:
      - key: OLLAMA_URL
        value: https://evaenespanol.loca.lt
      - key: MODEL_NAME
        value: neural-chat:7b
      - key: PORT
        sync: false # No sincronizar con el puerto asignado por Render
      - key: PYTHONUNBUFFERED
        value: "true" # Asegura que los logs se muestren inmediatamente
    
    # Configuración de autodespliegue desde GitHub
    autoDeploy: true